sudo: false
os:
  - osx
  - linux

language: node_js
node_js:
    - '8'
dist: trusty

before_install:
    - if [ $TRAVIS_OS_NAME == "linux" ]; then
        export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
        sleep 3;
      fi
install: |
      ./.travis/install.sh
script: |
      ./.travis/script.sh
deploy:
     provider: script
     script: ./.travis/deploy.sh
     skip_cleanup: true
     on:
       all_branches: true
cache: false
